### ISSUE TITLE
Compatibility errors with recent Node.js versions

### ISSUE THREAD

**Issue by ndr0n** [mjcella/facet#75]
Hey! I was trying to run facet but i get an issue on Ubuntu 22.04 when i run -> npm run facet after npm install.

the error that i get is the following:

TypeError: Cannot set property navigator of #<Object> which has only a getter
    at Object.<anonymous> (/home/esquilo/Storage/Programs/facet/node_modules/webmidi/dist/cjs/webmidi.cjs.min.js:445:4390)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at require (node:internal/modules/helpers:176:18)
    at Object.<anonymous> (/home/esquilo/Storage/Programs/facet/js/transport.js:4:19)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)

Node.js v21.1.0

Any help on making this run would be appreciated!

Thanks :)

**Comment by nnirror** [comment]
@ndr0n Thanks for adding this! I am able to duplicate this after installing Node v21.1.0.

I had been using v14.20.0 up to this point. So, as a workaround, if you change Node versions to v14.20.0, it should (hopefully) run on Ubuntu without this error.

But I will, of course, keep this issue so I can fix this error for newer Node versions.

**Comment by nnirror** [comment]
I have submitted [a ticket](https://github.com/djipco/webmidi/issues/392) to the WebMIDI repo, as after some more testing and process of elimination, I believe the issue is coming from the recently released node versions, and the `webmidi` npm package.

**Comment by nnirror** [comment]
Hey @ndr0n FYI if you want to use node v21 with Facet instead of switching to an older node version, you can.

To do so, edit the "scripts" object in `package.json` to look like this:

```
"scripts": {
    "facet": "node --no-experimental-global-navigator js/process_manager.js"
  }
```

I'm going keep this open until the fix goes out for WebMIDI, as they are still looking into it.

**Comment by nnirror** [comment]
@ndr0n Facet v1.1.6 was just released. It contains the updated WebMIDI package that has been fixed to address this issue. I just tested it on my local machine and it's working with Node v21.1.0 for me. Hopefully this fixes it for you. Thanks for pointing this out!
